### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by davepile** [valkalon/save-where-last-buffer-was#1]
Install on Windows 10 x64

Gave the following error. Not sure if install completed but the package was available to uninstall after installation. It did not work, if it was in fact installed

C:\Users\<username>\AppData\Local\atom\app-1.31.2\resources\app\apm\node_modules\temp\node_modules\rimraf\rimraf.js:218
      throw er
      ^

Error: EBUSY: resource busy or locked, unlink 'C:\Users\<8.3 version of username>\AppData\Local\Temp\apm-install-dir-11898-25136-1vs729j.pjtj'
    at Object.fs.unlinkSync (fs.js:1061:18)
    at rimrafSync (C:\Users\<username>\AppData\Local\atom\app-1.31.2\resources\app\apm\node_modules\temp\node_modules\rimraf\rimraf.js:211:13)
    at cleanupDirsSync (C:\Users\<username>\AppData\Local\atom\app-1.31.2\resources\app\apm\node_modules\temp\lib\temp.js:143:5)
    at process.cleanupSync (C:\Users\<username>\AppData\Local\atom\app-1.31.2\resources\app\apm\node_modules\temp\lib\temp.js:196:19)
    at emitOne (events.js:121:20)
    at process.emit (events.js:211:7)

**Comment by valkalon** [comment]
Hi @davepile thanks for the feedback and trying it out on Windows, I need to get my hands on a Window machine to investigate the issue, I'll  come back to you by the end of the week on this!

**Comment by valkalon** [comment]
It got faster than expected, after trying on a clean Win 10 x64 with atom1.31.2 I could not reproduce your error. Install was ok.

Are you able to install other plugins without any issue?

**Comment by davepile** [comment]
I am not a big atom user but I have installed other plugins without error. I will try on another computer when I get a chance and let you know

**Comment by davepile** [comment]
Hey I just tried again on the same PC that gave the error and it installed ok and works as advertised  :) 
Well done and thank you.

**Comment by valkalon** [comment]
Great! Glad it solved by itself and happy you enjoy it ;)
